#spring.application.name=weather
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/zerobase?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.show-sql=true
#spring.jpa.database=mysql

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: weather
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: mysql

logging:
  config: classpath:logback-spring.xml

openweathermap:
  key: ${OPEN_WEATHER_MAP_API_KEY}
